#!/bin/sh

./zad1
sleep 30
./zad1 5
sleep 30
./zad1 6
sleep 30
./zad1 11
sleep 30

./zad2
sleep 60
./zad2 3
sleep 60
./zad2 4
sleep 60
./zad2 10
sleep 60

./zad2_pid_avoid
sleep 60
./zad2_pid_avoid 7
sleep 60
./zad2_pid_avoid 10

